spring:
  resources:
    # TODO: how to add this programmatically
    add-mappings: false
  cloud:
    gateway:
      routes:
        test1:
          requestPath: /**
#          requestHost: '**.example.org'
          downstreamUrl: http://httpbin.org:80
